version: '3.9'

services:
  maximum_database:
    image: postgres:latest
    container_name: maximum_database_dev
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'postgres_maximum'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - maximum
    ports:
      - 127.0.0.1:5432:5432

volumes:
  database-data:      

networks:
  maximum:
    name: maximum
    external: false


